project_id = "dukohtdvhsdckizneksr"

[functions.chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.partner-api]
verify_jwt = false

[functions.send-launch-notifications]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.broadcast-notification]
verify_jwt = false
