project_id = "dukohtdvhsdckizneksr"

[functions.chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.partner-api]
verify_jwt = false

[functions.send-launch-notifications]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.broadcast-notification]
verify_jwt = false

[functions.zapier-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.purchase-credits]
verify_jwt = false

[functions.fulfill-credits]
verify_jwt = false
